version: "3.8"

services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
    image: pyflink-lab:1.19.1
    container_name: pyflink-jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.port: 8081
        parallelism.default: 1
    volumes:
      - ./pyflink_jobs:/opt/pyflink_jobs
      - ./data:/data
    depends_on:
      - kafka
      - postgres
      - mysql

  taskmanager:
    image: pyflink-lab:1.19.1
    container_name: pyflink-taskmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 1
    volumes:
      - ./pyflink_jobs:/opt/pyflink_jobs
      - ./data:/data
    depends_on:
      - jobmanager

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=flink
      - POSTGRES_PASSWORD=flink
      - POSTGRES_DB=flinkdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d

  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flinkdb
      - MYSQL_USER=flink
      - MYSQL_PASSWORD=flink
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/docker-entrypoint-initdb.d

networks:
  default:
    name: pyflink-net